version: 1.3.2
os: linux
files: 
        - source: /
          destination: /home/ec2-user/backend/zip/
          overwirte: yes
         
perimissions: 
 - object: /
   pattern: "**"
   owner: ec2-user
   group: ec2-user
   
hooks:
  ApplicationStart:
   - location: scripts/deploy.sh
     timeout: 60
     runas: ec2-user
