# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ cicd_test ]
  pull_request:
    branches: [ cicd_test ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
       
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn

      - name: bulid file
        run: yarn run build

      - name: Create env file
        run: |
          mkdir secret
          cd secret
          touch .env.development
          cat << EOF >> .env.development
          ${{ secrets.ENV }}
          EOF
          cd ../
          
      - name: Make tar file
        run: tar -cpvzf ./ssag.tgz *
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            ./ssag.tgz s3://ssag/ssag.tgz

      - name: Code Deploy
        run: aws deploy create-deployment --application-name EC2-S3-Deploy-BE --file-exists-behavior OVERWRITE --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name ssag --s3-location bucket=ssag,bundleType=tgz,key=$PROJECT_NAME/$GITHUB_SHA.tgz
